/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_list"];
    put?: never;
    post: operations["FeedbackController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback/{feedbackId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    FeedbackResponseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      /** @example manual */
      source: string;
      /** @example Please add keyboard shortcuts. */
      content: string;
      /** Format: date-time */
      occurredAt: string;
      /** Format: date-time */
      createdAt: string;
    };
    CreateFeedbackDto: {
      /**
       * @description Non-empty feedback text, up to 5000 characters
       * @example Please add keyboard shortcuts.
       */
      content: string;
    };
    ValidationErrorResponseDto: {
      /** @example 400 */
      statusCode: number;
      /** @example Bad Request */
      error: string;
      /**
       * @example [
       *       "Feedback must not be empty"
       *     ]
       */
      message: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"][];
        };
      };
    };
  };
  FeedbackController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFeedbackDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponseDto"];
        };
      };
    };
  };
  FeedbackController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"];
        };
      };
      /** @description Invalid UUID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
