/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_list"];
    put?: never;
    post: operations["FeedbackController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback/page": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_page"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback/{feedbackId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_detail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["FeedbackController_edit"];
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback/{feedbackId}/classification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_getClassification"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["FeedbackController_updateClassification"];
    trace?: never;
  };
  "/workspaces/{workspaceId}/feedback/{feedbackId}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["FeedbackController_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/product-areas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ClassificationController_listProductAreas"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/{workspaceId}/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ClassificationController_listTags"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    FeedbackResponseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      /** @example manual */
      source: string;
      /** @example Please add keyboard shortcuts. */
      content: string;
      /** @example 1 */
      version: number;
      /** Format: date-time */
      occurredAt: string;
      /** Format: date-time */
      createdAt: string;
    };
    FeedbackPageResponseDto: {
      items: components["schemas"]["FeedbackResponseDto"][];
      nextCursor: string | null;
    };
    FeedbackClassificationResponseDto: {
      /** Format: uuid */
      feedbackId: string;
      /** Format: uuid */
      productAreaId: string | null;
      tagIds: string[];
      /** @example 1 */
      version: number;
    };
    UpdateFeedbackClassificationDto: {
      /** Format: uuid */
      productAreaId: string | null;
      tagIds: string[];
      /** @example 1 */
      expectedVersion: number;
    };
    AuditEventResponseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      feedbackId: string;
      actorUserId: string;
      actorEmail: string | null;
      /** @enum {string} */
      action: "feedback.created" | "feedback.edited" | "feedback.classified";
      before: {
        [key: string]: unknown;
      } | null;
      after: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
    EditFeedbackDto: {
      /** @example Updated customer feedback */
      content: string;
      /** @example 1 */
      expectedVersion: number;
    };
    CreateFeedbackDto: {
      /**
       * @description Non-empty feedback text, up to 5000 characters
       * @example Please add keyboard shortcuts.
       */
      content: string;
      /**
       * Format: uuid
       * @description Reuse this key when retrying the same create request
       */
      requestKey?: string;
    };
    ValidationErrorResponseDto: {
      /** @example 400 */
      statusCode: number;
      /** @example Bad Request */
      error: string;
      /**
       * @example [
       *       "Feedback must not be empty"
       *     ]
       */
      message: string[];
    };
    ClassificationOptionResponseDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      workspaceId: string;
      /** @example Navigation */
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"][];
        };
      };
    };
  };
  FeedbackController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFeedbackDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponseDto"];
        };
      };
      /** @description Request key was already used for different feedback */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_page: {
    parameters: {
      query?: {
        limit?: number;
        /** @description Plain-text content search */
        q?: string;
        productAreaId?: string;
        tagId?: string;
        /** @description Cursor from the previous page */
        cursor?: string;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackPageResponseDto"];
        };
      };
      /** @description Invalid filter or cursor */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"];
        };
      };
      /** @description Invalid UUID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_edit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditFeedbackDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponseDto"];
        };
      };
      /** @description Invalid feedback edit */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Editor access required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback changed since it was loaded */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_getClassification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackClassificationResponseDto"];
        };
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_updateClassification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFeedbackClassificationDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackClassificationResponseDto"];
        };
      };
      /** @description Invalid classification input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Editor access required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback, area, or tag not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback changed since it was loaded */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedbackController_history: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        feedbackId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventResponseDto"][];
        };
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feedback not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ClassificationController_listProductAreas: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClassificationOptionResponseDto"][];
        };
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ClassificationController_listTags: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClassificationOptionResponseDto"][];
        };
      };
      /** @description Sign-in required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace access denied */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
